version: '3'

services: 
  microservicob:
    image: eduardobeserra/microservico-avancadev-b:latest
    ports: 
      - 9091:9091
  nginx:
    image: nginx
    volumes: 
      - ./html:/usr/share/nginx/html/
    ports:
      - 8080:80